/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_angelvasquez;

import java.util.ArrayList;
import java.util.Date;
import javafx.scene.chart.PieChart;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class Mian extends javax.swing.JFrame {

    /**
     * Creates new form Mian
     */
    public Mian() {
        initComponents();
        adimi.cargarArchivo();
        prductos = adimi.getListaproductos();
        Actualizar_Tabla();
    }

    public int codigoexist(String cod) {
        int num = -1;
        for (int i = 0; i < prductos.size(); i++) {
            if ((prductos.get(i).getCodigo() + "").equals(cod)) {
                num = i;
                i = prductos.size();
            }
        }
        return num;
    }

    public void Actualizar_Tabla() {
        jTable_Productos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Codigo", "Nombre", "Cantidadad", "Fecha Vencimiento", "Colorante"
                }
        ));
        DefaultTableModel modelot = (DefaultTableModel) jTable_Productos.getModel();
        for (int i = 0; i < prductos.size(); i++) {
            Object[] Nrow = {prductos.get(i).getCodigo(), prductos.get(i).getNombre(), prductos.get(i).getCant(), prductos.get(i).getFecha_vencimiento(), prductos.get(i).getColorante()};
            modelot.addRow(Nrow);
        }
        jTable_Productos.setModel(modelot);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearProducto = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tf_cnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_Codigo = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        sp_cantazu = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        sp_cantal = new javax.swing.JSpinner();
        jr_nacional = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        sp_clote = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jr_Azul = new javax.swing.JRadioButton();
        jr_Rojo = new javax.swing.JRadioButton();
        jr_verde = new javax.swing.JRadioButton();
        jr_Amarillo = new javax.swing.JRadioButton();
        jr_Blanco = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        sp_cprice = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jdc_fechavencimiento = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sp_cantidad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Productos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre");

        jLabel2.setText("Codigo");

        tf_Codigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("########"))));

        jLabel3.setText("Cantidad de Azucar");

        sp_cantazu.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, null, 1.0d));

        jLabel4.setText("Cantidad Alcohol");

        sp_cantal.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, 100.0d, 1.0d));

        jr_nacional.setText("Nacional");

        jLabel6.setText("Numero Lote");

        sp_clote.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Colorantes");

        jr_Azul.setText("Azul-4");

        jr_Rojo.setText("Rojo-69");

        jr_verde.setText("Verde-420");

        jr_Amarillo.setText("Amarillo-77");

        jr_Blanco.setText("Blanco-0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jr_Azul)
                        .addGap(18, 18, 18)
                        .addComponent(jr_Rojo)
                        .addGap(18, 18, 18)
                        .addComponent(jr_verde)
                        .addGap(18, 18, 18)
                        .addComponent(jr_Amarillo)
                        .addGap(18, 18, 18)
                        .addComponent(jr_Blanco)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr_Azul)
                    .addComponent(jr_Rojo)
                    .addComponent(jr_verde)
                    .addComponent(jr_Amarillo)
                    .addComponent(jr_Blanco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Precio");

        sp_cprice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.5d));

        jLabel9.setText("Fecha de Vencimiento");

        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel5.setText("Cantidad");

        sp_cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jd_crearProductoLayout = new javax.swing.GroupLayout(jd_crearProducto.getContentPane());
        jd_crearProducto.getContentPane().setLayout(jd_crearProductoLayout);
        jd_crearProductoLayout.setHorizontalGroup(
            jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearProductoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearProductoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(sp_cprice, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jdc_fechavencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_crearProductoLayout.createSequentialGroup()
                            .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_crearProductoLayout.createSequentialGroup()
                                    .addComponent(jr_nacional)
                                    .addGap(133, 133, 133)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(sp_clote, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_crearProductoLayout.createSequentialGroup()
                                    .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jd_crearProductoLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(sp_cantazu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jd_crearProductoLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(tf_cnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jd_crearProductoLayout.createSequentialGroup()
                                            .addGap(103, 103, 103)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sp_cantal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jd_crearProductoLayout.createSequentialGroup()
                                            .addGap(63, 63, 63)
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(189, 189, 189))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jd_crearProductoLayout.setVerticalGroup(
            jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearProductoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_cnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(sp_cantazu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(sp_cantal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr_nacional)
                    .addComponent(jLabel6)
                    .addComponent(sp_clote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sp_cprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addComponent(jdc_fechavencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_crearProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_crearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidadad", "Fecha Vencimiento", "Colorante"
            }
        ));
        jScrollPane1.setViewportView(jTable_Productos);

        jMenu1.setText("Agregar");

        jMenuItem1.setText("Agregar Producto");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            if (codigoexist(tf_Codigo.getText()) == -1) {
                char nal = 'n';
                if (jr_nacional.isSelected()) {
                    nal = 's';
                }
                String col = "";
                if (jr_Amarillo.isSelected()) {
                    col += jr_Amarillo.getText() + ",";
                }
                if (jr_Azul.isSelected()) {
                    col += jr_Azul.getText() + ",";
                }
                if (jr_Blanco.isSelected()) {
                    col += jr_Blanco.getText() + ",";
                }
                if (jr_Rojo.isSelected()) {
                    col += jr_Rojo.getText() + ",";
                }
                if (jr_verde.isSelected()) {
                    col += jr_verde.getText() + ",";
                }
                prductos.add(new Producto(Integer.parseInt(tf_Codigo.getText()), tf_cnombre.getText(), (Double) sp_cantazu.getValue(), (Double) sp_cantal.getValue(), nal, (Integer) sp_clote.getValue(), col, (Double) sp_cprice.getValue(), (Integer) sp_cantidad.getValue(), jdc_fechavencimiento.getDate()));
                JOptionPane.showMessageDialog(jd_crearProducto, "Producto creado exitosamente");
            } else {
                JOptionPane.showMessageDialog(jd_crearProducto, "Cree otro codigo");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_crearProducto, "Ocurrio un errorS");
        }

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Productos;
    private javax.swing.JDialog jd_crearProducto;
    private com.toedter.calendar.JDateChooser jdc_fechavencimiento;
    private javax.swing.JRadioButton jr_Amarillo;
    private javax.swing.JRadioButton jr_Azul;
    private javax.swing.JRadioButton jr_Blanco;
    private javax.swing.JRadioButton jr_Rojo;
    private javax.swing.JRadioButton jr_nacional;
    private javax.swing.JRadioButton jr_verde;
    private javax.swing.JSpinner sp_cantal;
    private javax.swing.JSpinner sp_cantazu;
    private javax.swing.JSpinner sp_cantidad;
    private javax.swing.JSpinner sp_clote;
    private javax.swing.JSpinner sp_cprice;
    private javax.swing.JFormattedTextField tf_Codigo;
    private javax.swing.JTextField tf_cnombre;
    // End of variables declaration//GEN-END:variables
    AdminProducto adimi = new AdminProducto("./Productos.txt");
    ArrayList<Producto> prductos = new ArrayList();
}
